apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: demo-app-patch.yaml
  target:
    kind: Deployment
    name: demo-app
- path: demo2-app-patch.yaml
  target:
    kind: Deployment
    name: demo2-app

images:
- name: demo-app
  newName: your-registry.com/demo-app
  newTag: v1.0.0
- name: demo2-app
  newName: your-registry.com/demo2-app
  newTag: v1.0.0 