apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces.yaml
- deployments.yaml
- services.yaml
- ingress.yaml

images:
- name: demo-app
  newTag: latest
- name: demo2-app
  newTag: latest 